teleop_twist_joy_node:
  ros__parameters:
    axis_linear:
      x: 1
    scale_linear:
      x: 0.25
    scale_linear_turbo:
      x: 0.5
    axis_angular:
      yaw: 3
    scale_angular:
      yaw: 1.57
    scale_angular_turbo:
      yaw: 3.14
    enable_button: 4
    enable_turbo_button: 5
